# Generated by Django 3.0.3 on 2020-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customer_ip',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
